# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[directory]
style = "blue"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[rust]
disabled = true

[lua]
disabled = true

[aws]
disabled = true
